version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: sunday
    commit-message:
      prefix: ci
    labels:
      - dependencies
    groups:
      actions:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
    versioning-strategy: increase
    commit-message:
      prefix: chore
    labels:
      - dependencies
    groups:
      npm:
        patterns: ['*']
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
